// Generated by CoffeeScript 1.8.0
(function() {
  var RegexDynamicValue;

  RegexDynamicValue = function() {
    this.evaluate = function() {
      var regex;
      regex = new RegExp(this.regex, 'g');
      if (this.input) {
        return this.input.replace(regex, this.replacement);
      }
    };
    this.title = function() {
      if (this.regex && this.regex.length > 0) {
        return this.regex;
      }
      return "Regexp";
    };
    this.text = function() {
      if (this.input && this.input.length > 0) {
        return "" + this.input;
      }
      return null;
    };
  };

  RegexDynamicValue.identifier = "com.luckymarmot.PawExtensions.RegexDynamicValue";

  RegexDynamicValue.title = "Regex Dynamic Value";

  RegexDynamicValue.inputs = [DynamicValueInput("regex", "Regex", "String"), DynamicValueInput("input", "Input", "String"), DynamicValueInput("replacement", "Replacement", "String")];

  registerDynamicValueClass(RegexDynamicValue);

}).call(this);
